Add conditional rerun to workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,17 +4,36 @@ on:
   push:
   workflow_dispatch: # Allow for running this manually.
 
+
+# Example of partial rerun of GitHub Actions workflow
+#  https://github.com/alteral/re-run-only-failed-jobs-on-github-actions/actions/runs/760987512/workflow
 jobs:
-  build:
+  fail:
     runs-on: ${{ matrix.os }}
+    name: Failed
     strategy:
       matrix:
         os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15, windows-2022, windows-2019, windows-2016]
         java: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
       fail-fast: false
     steps:
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +%s)"
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-
+      - name: Get the previous run result
+        id: run_result
+        run: cat run_result 2>/dev/null || echo 'default'
+
       - name: Check out Git repository
         uses: actions/checkout@v2
+        if: steps.run_result.outputs.run_result != 'success'
       - name: Install Java and Maven
         uses: actions/setup-java@v2
         with:
@@ -22,5 +41,45 @@ jobs:
           java-version: ${{ matrix.java }}
       - name: Maven version
         run: mvn --version # Potentially make a check for Maven to be 3.8.3 or higher
-      - name: Compile source-code
+      - if: steps.run_result.outputs.run_result != 'success'
         run: mvn -U clean install -q
+      - run: echo "::set-output name=run_result::success" > run_result
+
+  success:
+    runs-on: ${{ matrix.os }}
+    name: Passed
+    strategy:
+      matrix:
+        os: [ ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15, windows-2022, windows-2019, windows-2016 ]
+        java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
+      fail-fast: false
+    steps:
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +'%Y-%m-%dT%H:%M:%S')"
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-
+      - name: Get the previous run result
+        id: run_result
+        run: cat run_result 2>/dev/null || echo 'default'
+
+      - name: Check out Git repository
+        uses: actions/checkout@v2
+        if: steps.run_result.outputs.run_result != 'success'
+      - name: Install Java and Maven
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'zulu'
+          java-version: ${{ matrix.java }}
+      - name: Maven version
+        run: mvn --version # Potentially make a check for Maven to be 3.8.3 or higher
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: mvn -U clean install -q
+      - run: echo "::set-output name=run_result::success" > run_result
+
+
