Diable success step for Windows workflow

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -26,10 +26,11 @@ jobs:
           key: ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-${{ steps.timestamp.outputs.timestamp }}
           restore-keys: |
             ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-
-      - name: List files
-        run: ls
+      - name: List files in folder and sub-folders
+        run: dir /s /b /o:gn
       - name: Get the previous run result
         id: run_result
+        # TODO: Fix this part of the pipeline
         run: cat run_result 2> nul; if (!$?) { echo 'default' }
       - name: Check out Git repository
         uses: actions/checkout@v2
@@ -47,41 +48,41 @@ jobs:
       - name: Save results
         run: echo "::set-output name=run_result::success" > run_result
 
-  success:
-    runs-on: ${{ matrix.os }}
-    name: Passed
-    strategy:
-      matrix:
-        os: [ windows-2022, windows-2019, windows-2016 ]
-        java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
-      fail-fast: false
-    steps:
-      - name: Save timestamp
-        id: timestamp
-        run: echo "::set-output name=timestamp::$(get-date -f 'yyyy/MM/dd hh:mm:ss tt')"
-      - name: Restore the previous run result
-        uses: actions/cache@v2
-        with:
-          path: |
-            run_result
-          key: ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-${{ steps.timestamp.outputs.timestamp }}
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-
-      - name: Get the previous run results
-        id: run_result
-        run: cat run_result 2> nul; if (!$?) { echo 'default' }
-      - name: Check out Git repository
-        uses: actions/checkout@v2
-        if: steps.run_result.outputs.run_result != 'success'
-      - name: Install Java and Maven
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'zulu'
-          java-version: ${{ matrix.java }}
-      - name: Maven version
-        run: mvn --version # Potentially make a check for Maven to be 3.8.3 or higher
-      - name: Build project
-        if: steps.run_result.outputs.run_result != 'success'
-        run: mvn clean install -q
-      - name: Save results
-        run: echo "::set-output name=run_result::success" > run_result
+#  success:
+#    runs-on: ${{ matrix.os }}
+#    name: Passed
+#    strategy:
+#      matrix:
+#        os: [ windows-2022, windows-2019, windows-2016 ]
+#        java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
+#      fail-fast: false
+#    steps:
+#      - name: Save timestamp
+#        id: timestamp
+#        run: echo "::set-output name=timestamp::$(get-date -f 'yyyy/MM/dd hh:mm:ss tt')"
+#      - name: Restore the previous run result
+#        uses: actions/cache@v2
+#        with:
+#          path: |
+#            run_result
+#          key: ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-${{ steps.timestamp.outputs.timestamp }}
+#          restore-keys: |
+#            ${{ github.run_id }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.java }}-
+#      - name: Get the previous run results
+#        id: run_result
+#        run: cat run_result 2> nul; if (!$?) { echo 'default' }
+#      - name: Check out Git repository
+#        uses: actions/checkout@v2
+#        if: steps.run_result.outputs.run_result != 'success'
+#      - name: Install Java and Maven
+#        uses: actions/setup-java@v2
+#        with:
+#          distribution: 'zulu'
+#          java-version: ${{ matrix.java }}
+#      - name: Maven version
+#        run: mvn --version # Potentially make a check for Maven to be 3.8.3 or higher
+#      - name: Build project
+#        if: steps.run_result.outputs.run_result != 'success'
+#        run: mvn clean install -q
+#      - name: Save results
+#        run: echo "::set-output name=run_result::success" > run_result
